---
# file: tasks/installation.yml
#
# installation tasks.
#

- name: installation | ensure bind9 and dnsutils are installed
  ansible.builtin.apt:
    name="{{ item }}"
    state=present
  with_items:
    - bind9
    - dnsutils

- name: installation | ensure log directory is present
  ansible.builtin.file:
    path="{{ bind_dir_log }}"
    state=directory
    owner=bind
    group=bind
    mode=0755
