---
# file: bind/tasks/main.yml
#
# tasks file
#

- ansible.builtin.include_tasks: debug.yml
  when: debug | default(false)
  tags: debug

- ansible.builtin.include_tasks: validation.yml
  tags: validation

- ansible.builtin.include_tasks: installation.yml
  tags: installation
  sudo: yes

- ansible.builtin.include_tasks: configuration.yml
  tags: configuration
  sudo: yes

- ansible.builtin.include_tasks: apparmor.yml
  tags: apparmor
  sudo: yes
